version: '2.1'

services:
  php:
      build:
        context: ../docker_files
        dockerfile: php
      restart: unless-stopped
      environment:
        PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
      links:
        - db
      volumes:
        - ../app/back:/var/www/back
        - ../app/front:/var/www/front
        - ./php.ini:/usr/local/etc/php/conf.d/common.ini
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_ARBITRARY=1
       - UPLOAD_LIMIT=99999999999999
      restart: always
      ports:
       - "8090:80"
      volumes:
       - ../sessions
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ../app/front/public:/var/www/front
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --noninteractive --keep-until-expiring --webroot --webroot-path=/var/www/front/static/letsencrypt --email andrei.prozorov@mail.ru --agree-tos --no-eff-email -d www.gsk-stroy.ru -d gsk-stroy.ru #--dry-run
  web:
      image: nginx:1.11-alpine
      restart: unless-stopped
      links:
        - php
      ports:
        - "8080:8080"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
      volumes_from:
        - php
        - certbot
  node:
      image: "node:latest"
      user: "www-data"
      working_dir: /var/www/front
      restart: unless-stopped
      environment:
        - NODE_ENV=production
      volumes_from:
        - certbot
      ports:
        - "443:3001"
        - "80:3000"
      command: "node /var/www/front/__sapper__/build"
      links:
        - web
  db:
        image: mysql:5.7.23
        restart: unless-stopped
        env_file:
          - ../app/back/.env.local
        environment:
         - TZ=Europe/Moscow
        command: --innodb_use_native_aio=0
        volumes:
          - ../db:/var/lib/mysql
