version: '2.1'

services:
  php:
    build:
      context: ../docker_files
      dockerfile: php
    restart: unless-stopped
    environment:
      PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
    links:
      - db
    volumes:
      - ../app/back:/var/www/back
      - ./php.ini:/usr/local/etc/php/conf.d/common.ini
      - ../logs/php/php-error.log:/var/log/error.log
      - ../logs/php/php-access.log:/var/log/access.log
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "3m"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=99999999999999
    restart: unless-stopped
    links:
      - db
    volumes:
      - ../sessions
    ports:
      - "8090:80"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "3m"
  certbot:
    image: certbot/certbot
    depends_on:
      - "node"
    restart: unless-stopped
    volumes:
      - ../app/front:/var/www/front
      - ./certbot-etc:/etc/letsencrypt
      - ../logs/letsencrypt:/var/log/letsencrypt
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew ; sleep 12h & wait $${!}; done;'"
    command: certonly --noninteractive --keep-until-expiring --webroot --webroot-path=/var/www/front/public/static/letsencrypt --email docentovich@gmail.com --agree-tos --no-eff-email -d gsk-stroy.ru -d www.gsk-stroy.ru #--dry-run
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "3m"
  web:
    image: nginx:1.11-alpine
    restart: unless-stopped
    links:
      - php
    ports:
      - "8080:8080"
    command: [/bin/sh, '-c', 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"''']
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../app/back:/var/www/back
      - ../logs/nginx:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "3m"
  node:
    image: "node:latest"
    user: "www-data"
    working_dir: /var/www/front/public
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ../app/front:/var/www/front
    ports:
      - "443:3001"
      - "80:3000"
    command: "node /var/www/front/public/__sapper__/build"
    links:
      - web
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "3m"
  db:
    image: mariadb
    restart: unless-stopped
    env_file:
      - ../app/back/.env.local
    environment:
      - TZ=Europe/Moscow
    command: --innodb_use_native_aio=0
    volumes:
      - ../db:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "3m"
