version: '2'

services:
  php:
    build:
      context: ../docker_files
      dockerfile: php
    environment:
      PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
    links:
      - db
    volumes:
      - ../app/back:/var/www/back
      - ../app/front:/var/www/front
      - ./php.ini:/usr/local/etc/php/conf.d/common.ini
  web:
    image: nginx:1.11-alpine
    links:
      - php
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  db:
    image: mysql:5.7.23
    env_file:
      - ../app/back/.env.local
    environment:
      - TZ=Europe/Moscow
    command: --innodb_use_native_aio=0
    volumes:
      - ../db:/var/lib/mysql
